doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    storage:
        # Default (SQL table) metadata storage configuration
        # https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at' #'executedAt' for underscore number aware naming strategy
            execution_time_column_name: 'execution_time' #'executionTime' for underscore number aware naming strategy
