doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    # transferred from old config
    storage:
        # Default (SQL table) metadata storage configuration
        # https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executedAt' #'executed_at' for underscore naming strategy
            execution_time_column_name: 'executionTime' #'execution_time' for underscore naming strategy
