framework:
    secret: '%env(APP_SECRET)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # With this config, PHP's native session handling is used
        handler_id: ~
        #cookie_samesite: lax

    assets: ~
    csrf_protection: ~
    fragments: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true
