security:
    encoders:
        App\Entity\User:
            algorithm: 'auto'

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous:
                lazy: true
            pattern: ^/
            form_login:
                check_path: /login
                # Activate CSRF protection for login form
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
            logout: ~

    access_control:
        # Allow access to login form unauthenticated users
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # This line was fixed (accessible to all before!!) to allow only "admin" users
        # to perform actions as concerns other users!
        - { path: ^/users, roles: ROLE_ADMIN }
        # Allow authenticated users to access pages which do not concern users management
        - { path: ^/, roles: ROLE_USER }

